# config.yaml
shared:
  batch_size: 12
  num_workers: 4
  num_class: 4
  kernel_size: 1
  num_repeat_kernel: 1
  grid_size: 64

training:
  num_epoch: 30
  learning_rate: 0.001
  weight_decay: 0.0001

  # Data
  do_update_caching: false
  do_preprocess: true
  frac_training: 0.65
  frac_testing: 1
  crop_ratio: 0.8
  crop_radius: 5
  probability: 0.5
  n_augmentations: 1
  
  # Model loading / saving
  load_model: true
  resume_optimizer: false 
  model_path: "./models/pretrained/model_KDE.tar"

  # Class weighting 
  use_class_weights: true             # set true if training dataset is imbalanced

  # Dataset paths
  ROOT_DIR: './data/Val_arpette/'
  TRAIN_FILES: 'modeltrees_train.csv'
  TEST_FILES: 'modeltrees_test.csv'

inference:
  do_preprocess: false
  do_update_caching: false
  verbose: true

  # Paths
  src_inf_root: "./inference/"
  src_inf_data: "data/Part"
  src_inf_results: "test_results"
  src_model: "./log/train_19/model_KDE.tar"
  inference_file: "modeltrees_inference.csv"
